# Generated by Django 3.2.9 on 2021-12-09 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20211204_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('salary', models.FloatField(max_length=40)),
                ('image', models.FileField(upload_to='')),
                ('experience', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=300)),
                ('skills', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('creationdate', models.DateField()),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.recruiteruser')),
            ],
        ),
    ]
